pub struct Exercise {
    pub slug:          &'static str,
    pub title:         &'static str,
    pub readme:        &'static str,
    pub hints:         &'static str,
    pub solution:      &'static str,
    pub c_source:      &'static str,
    pub compile_flags: &'static [&'static str],
    pub flag:          &'static str,
}

pub const EXERCISES: &[Exercise] = &[
    Exercise {
        slug:          "01_gdb_basics",
        title:         "GDB Basics — Calling Hidden Functions",
        readme:        include_str!("../assets/01_gdb_basics/README"),
        hints:         include_str!("../assets/01_gdb_basics/hints"),
        solution:      include_str!("../assets/01_gdb_basics/solution"),
        c_source:      include_str!("../assets/01_gdb_basics/target.c"),
        compile_flags: &["-g"],
        flag:          "HRZ{call_is_power}",
    },
    Exercise {
        slug:          "02_gdb_variables",
        title:         "GDB Variables — Rewriting Memory",
        readme:        include_str!("../assets/02_gdb_variables/README"),
        hints:         include_str!("../assets/02_gdb_variables/hints"),
        solution:      include_str!("../assets/02_gdb_variables/solution"),
        c_source:      include_str!("../assets/02_gdb_variables/target.c"),
        compile_flags: &["-g"],
        flag:          "HRZ{memory_bends}",
    },
    Exercise {
        slug:          "03_gdb_crash",
        title:         "GDB Crash Analysis — Backtrace",
        readme:        include_str!("../assets/03_gdb_crash/README"),
        hints:         include_str!("../assets/03_gdb_crash/hints"),
        solution:      include_str!("../assets/03_gdb_crash/solution"),
        c_source:      include_str!("../assets/03_gdb_crash/target.c"),
        compile_flags: &["-g"],
        flag:          "HRZ{null_speaks}",
    },
    Exercise {
        slug:          "04_valgrind_leak",
        title:         "Valgrind — Memory Leak",
        readme:        include_str!("../assets/04_valgrind_leak/README"),
        hints:         include_str!("../assets/04_valgrind_leak/hints"),
        solution:      include_str!("../assets/04_valgrind_leak/solution"),
        c_source:      include_str!("../assets/04_valgrind_leak/target.c"),
        compile_flags: &["-g"],
        flag:          "HRZ{leak_found}",
    },
    Exercise {
        slug:          "05_valgrind_uaf",
        title:         "Valgrind — Use-After-Free",
        readme:        include_str!("../assets/05_valgrind_uaf/README"),
        hints:         include_str!("../assets/05_valgrind_uaf/hints"),
        solution:      include_str!("../assets/05_valgrind_uaf/solution"),
        c_source:      include_str!("../assets/05_valgrind_uaf/target.c"),
        compile_flags: &["-g"],
        flag:          "HRZ{dangling_ptr}",
    },
    Exercise {
        slug:          "06_valgrind_invalid_read",
        title:         "Valgrind — Invalid Read (Buffer Overread)",
        readme:        include_str!("../assets/06_valgrind_invalid_read/README"),
        hints:         include_str!("../assets/06_valgrind_invalid_read/hints"),
        solution:      include_str!("../assets/06_valgrind_invalid_read/solution"),
        c_source:      include_str!("../assets/06_valgrind_invalid_read/target.c"),
        compile_flags: &["-g"],
        flag:          "HRZ{one_too_many}",
    },
    Exercise {
        slug:          "07_return_oriented",
        title:         "Return-Oriented Hijacking",
        readme:        include_str!("../assets/07_return_oriented/README"),
        hints:         include_str!("../assets/07_return_oriented/hints"),
        solution:      include_str!("../assets/07_return_oriented/solution"),
        c_source:      include_str!("../assets/07_return_oriented/target.c"),
        compile_flags: &["-fno-stack-protector", "-no-pie"],
        flag:          "HRZ{ret_hijacked}",
    },
    Exercise {
        slug:          "08_shellcode",
        title:         "Shellcode Injection",
        readme:        include_str!("../assets/08_shellcode/README"),
        hints:         include_str!("../assets/08_shellcode/hints"),
        solution:      include_str!("../assets/08_shellcode/solution"),
        c_source:      include_str!("../assets/08_shellcode/target.c"),
        compile_flags: &["-fno-stack-protector", "-z", "execstack", "-no-pie"],
        flag:          "HRZ{code_injected}",
    },
    Exercise {
        slug:          "09_off_by_one",
        title:         "Off-by-One",
        readme:        include_str!("../assets/09_off_by_one/README"),
        hints:         include_str!("../assets/09_off_by_one/hints"),
        solution:      include_str!("../assets/09_off_by_one/solution"),
        c_source:      include_str!("../assets/09_off_by_one/target.c"),
        compile_flags: &["-fno-stack-protector", "-no-pie"],
        flag:          "HRZ{one_byte_king}",
    },
    Exercise {
        slug:          "10_format_string",
        title:         "Format String Attack",
        readme:        include_str!("../assets/10_format_string/README"),
        hints:         include_str!("../assets/10_format_string/hints"),
        solution:      include_str!("../assets/10_format_string/solution"),
        c_source:      include_str!("../assets/10_format_string/target.c"),
        compile_flags: &["-no-pie"],
        flag:          "HRZ{fmt_writer}",
    },
    Exercise {
        slug:          "11_ret2libc",
        title:         "Return-to-libc (NX Bypass)",
        readme:        include_str!("../assets/11_ret2libc/README"),
        hints:         include_str!("../assets/11_ret2libc/hints"),
        solution:      include_str!("../assets/11_ret2libc/solution"),
        c_source:      include_str!("../assets/11_ret2libc/target.c"),
        compile_flags: &["-fno-stack-protector", "-no-pie"],
        flag:          "HRZ{rop_and_roll}",
    },
];
